language: node_js
node_js:
  - 15
before_install:
  - npm install -g npm@latest
  - npm install -g codecov
  - npm install -g c8
install:
  - npm install --dev
script:
  - npm test
after_success:
  - npm run coverage
